services:
  dvc:
    container_name: DVC
    build:
      context: .
      dockerfile: DockerfileDVC
    volumes:
      - ./aws:/root/.aws
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: ["sh", "dvcpull.sh"]